export const CITY_TZ: { city: string; tz: string }[] = [
  // 中文
  { city: '北京',   tz: 'Asia/Shanghai' },
  { city: '上海',   tz: 'Asia/Shanghai' },
  { city: '广州',   tz: 'Asia/Shanghai' },
  { city: '深圳',   tz: 'Asia/Shanghai' },
  { city: '成都',   tz: 'Asia/Shanghai' },
  { city: '武汉',   tz: 'Asia/Shanghai' },
  { city: '杭州',   tz: 'Asia/Shanghai' },
  { city: '南京',   tz: 'Asia/Shanghai' },
  { city: '西安',   tz: 'Asia/Shanghai' },
  { city: '重庆',   tz: 'Asia/Shanghai' },
  { city: '香港',   tz: 'Asia/Hong_Kong' },
  { city: '台北',   tz: 'Asia/Taipei' },
  { city: '澳门',   tz: 'Asia/Macau' },
  { city: '东京',   tz: 'Asia/Tokyo' },
  { city: '大阪',   tz: 'Asia/Tokyo' },
  { city: '首尔',   tz: 'Asia/Seoul' },
  { city: '新加坡', tz: 'Asia/Singapore' },
  { city: '吉隆坡', tz: 'Asia/Kuala_Lumpur' },
  { city: '曼谷',   tz: 'Asia/Bangkok' },
  { city: '雅加达', tz: 'Asia/Jakarta' },
  { city: '孟买',   tz: 'Asia/Kolkata' },
  { city: '迪拜',   tz: 'Asia/Dubai' },
  { city: '莫斯科', tz: 'Europe/Moscow' },
  { city: '伦敦',   tz: 'Europe/London' },
  { city: '巴黎',   tz: 'Europe/Paris' },
  { city: '柏林',   tz: 'Europe/Berlin' },
  { city: '罗马',   tz: 'Europe/Rome' },
  { city: '马德里', tz: 'Europe/Madrid' },
  { city: '阿姆斯特丹', tz: 'Europe/Amsterdam' },
  { city: '伊斯坦布尔', tz: 'Europe/Istanbul' },
  { city: '开罗',   tz: 'Africa/Cairo' },
  { city: '纽约',   tz: 'America/New_York' },
  { city: '波士顿', tz: 'America/New_York' },
  { city: '迈阿密', tz: 'America/New_York' },
  { city: '芝加哥', tz: 'America/Chicago' },
  { city: '洛杉矶', tz: 'America/Los_Angeles' },
  { city: '旧金山', tz: 'America/Los_Angeles' },
  { city: '西雅图', tz: 'America/Los_Angeles' },
  { city: '温哥华', tz: 'America/Vancouver' },
  { city: '多伦多', tz: 'America/Toronto' },
  { city: '悉尼',   tz: 'Australia/Sydney' },
  { city: '墨尔本', tz: 'Australia/Melbourne' },
  { city: '奥克兰', tz: 'Pacific/Auckland' },
  // English
  { city: 'Beijing',       tz: 'Asia/Shanghai' },
  { city: 'Shanghai',      tz: 'Asia/Shanghai' },
  { city: 'Guangzhou',     tz: 'Asia/Shanghai' },
  { city: 'Shenzhen',      tz: 'Asia/Shanghai' },
  { city: 'Chengdu',       tz: 'Asia/Shanghai' },
  { city: 'Hong Kong',     tz: 'Asia/Hong_Kong' },
  { city: 'Taipei',        tz: 'Asia/Taipei' },
  { city: 'Tokyo',         tz: 'Asia/Tokyo' },
  { city: 'Osaka',         tz: 'Asia/Tokyo' },
  { city: 'Seoul',         tz: 'Asia/Seoul' },
  { city: 'Singapore',     tz: 'Asia/Singapore' },
  { city: 'Kuala Lumpur',  tz: 'Asia/Kuala_Lumpur' },
  { city: 'Bangkok',       tz: 'Asia/Bangkok' },
  { city: 'Jakarta',       tz: 'Asia/Jakarta' },
  { city: 'Mumbai',        tz: 'Asia/Kolkata' },
  { city: 'Dubai',         tz: 'Asia/Dubai' },
  { city: 'Istanbul',      tz: 'Europe/Istanbul' },
  { city: 'Moscow',        tz: 'Europe/Moscow' },
  { city: 'London',        tz: 'Europe/London' },
  { city: 'Paris',         tz: 'Europe/Paris' },
  { city: 'Berlin',        tz: 'Europe/Berlin' },
  { city: 'Amsterdam',     tz: 'Europe/Amsterdam' },
  { city: 'Madrid',        tz: 'Europe/Madrid' },
  { city: 'Rome',          tz: 'Europe/Rome' },
  { city: 'New York',      tz: 'America/New_York' },
  { city: 'Chicago',       tz: 'America/Chicago' },
  { city: 'Los Angeles',   tz: 'America/Los_Angeles' },
  { city: 'San Francisco', tz: 'America/Los_Angeles' },
  { city: 'Seattle',       tz: 'America/Los_Angeles' },
  { city: 'Vancouver',     tz: 'America/Vancouver' },
  { city: 'Toronto',       tz: 'America/Toronto' },
  { city: 'Sydney',        tz: 'Australia/Sydney' },
  { city: 'Melbourne',     tz: 'Australia/Melbourne' },
  { city: 'Auckland',      tz: 'Pacific/Auckland' },
]

export function matchCityTz(input: string): string | null {
  if (!input.trim()) return null
  const lower = input.toLowerCase()
  const match = CITY_TZ.find(c => c.city.toLowerCase().startsWith(lower))
  return match?.tz ?? null
}
